In [6]:
import cv2 as cv
import os
import numpy as np
import matplotlib.pyplot as plt

In [7]:
#directories
dataset_dir = 'dataset'
output_dir ="output"
g_matrix_filename = "G.npy"

In [8]:
#store the computed images on disk
save_output = False

In [9]:
def load_images_from_folder(folder):
    images = []
    for filename in os.listdir(folder):
        img = cv.imread(os.path.join(folder,filename))
        if img is not None:
            images.append(img)
    return images

In [10]:
imgs = load_images_from_folder(dataset_dir)
n = len(imgs)

In [11]:
G = np.load(os.path.join(output_dir,g_matrix_filename))

In [12]:
i=0
j=0
print(G[3*i:3*(i+1),3*j:3*(j+1)])

[[-5. -0. -0.]
 [-0. -5. -0.]
 [-0. -0. -5.]]


In [13]:
 u,d,v = cv.SVDecomp(G)

In [16]:
print(G.shape, u.shape, d.shape, v.shape)

(60, 60) (60, 1) (60, 60) (60, 60)


In [22]:
cosa=u*np.sqrt(d)
print(cosa.shape)
print(d)


(60, 60)
[[ 3.99910136e-02 -5.19761672e-01  5.93248895e-02 ... -1.99141801e-05
  -7.36100261e-05 -2.95066218e-05]
 [ 5.03690002e-04 -3.15857784e-02  4.04692724e-03 ...  8.50428695e-05
   5.86778121e-05 -2.39881707e-04]
 [-2.70897445e-04 -8.90252280e-05  7.31833614e-06 ...  2.24820080e-01
  -4.95233080e-02  2.69350027e-01]
 ...
 [-2.08028260e-02 -5.15701227e-01  5.95958543e-02 ... -2.47752846e-05
  -7.21341145e-05 -2.87290643e-05]
 [-7.85527329e-04 -4.12941636e-02  5.20846492e-03 ...  8.47649555e-05
   5.83799310e-05 -2.39688845e-04]
 [-2.65566613e-04 -3.90669329e-05  6.99280981e-07 ...  2.25530421e-01
  -6.93268761e-02  2.63651112e-01]]


<ipython-input-22-91563ae161f3>:1: RuntimeWarning: invalid value encountered in sqrt
  cosa=u*np.sqrt(d)
